# Generated by Django 4.1.2 on 2023-03-27 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0025_remove_studentprofile_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='college.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Sem',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Sem3', 'Sem3'), ('Sem4', 'Sem4'), ('Sem5', 'Sem5')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
