# Generated by Django 4.1.2 on 2023-03-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0026_studentprofile_course_id_studentprofile_sem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='Course_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Sem',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Student_id',
        ),
    ]
