# Generated by Django 4.1.2 on 2023-03-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0027_remove_studentprofile_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Sem',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Sem3', 'Sem3'), ('Sem4', 'Sem4'), ('Sem5', 'Sem5')], default='', max_length=100),
        ),
    ]
