# Generated by Django 4.1.2 on 2023-03-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_delete_user'),
        ('assignments', '0029_studentprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='college.course'),
        ),
    ]
