# Generated by Django 4.1.2 on 2023-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0030_studentprofile_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='Sem',
            field=models.CharField(default='', max_length=100),
        ),
    ]
