# Generated by Django 4.1.2 on 2023-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('photo', models.ImageField(upload_to='event/')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
