# Generated by Django 4.1.2 on 2023-03-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='photo',
            new_name='Photo',
        ),
    ]
