# Generated by Django 4.1.2 on 2023-03-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_delete_profile'),
        ('college', '0005_rename_description_course_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
