# Generated by Django 4.1.2 on 2023-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(upload_to='')),
                ('Coursename', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
