# Generated by Django 4.1.2 on 2023-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_alter_subscribe_current_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='current_datetime',
        ),
    ]
