# Generated by Django 4.1.2 on 2023-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_remove_subscribe_current_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
    ]
