# Generated by Django 4.1.2 on 2023-03-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
