# Generated by Django 4.1.2 on 2023-05-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
