# Generated by Django 4.1.2 on 2023-05-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
