# Generated by Django 4.1.2 on 2023-05-14 10:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=tinymce.models.HTMLField(),
        ),
    ]
