# Generated by Django 4.1.2 on 2023-05-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.TextField(),
        ),
    ]
