# Generated by Django 4.1.2 on 2023-03-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_contact_profile_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
