# Generated by Django 4.1.2 on 2023-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='Contact',
            field=models.CharField(max_length=100),
        ),
    ]
