# Generated by Django 4.1.2 on 2023-03-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_course'),
        ('assignments', '0005_alter_teacherprofile_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjectname', models.CharField(max_length=100)),
                ('Subjectcode', models.IntegerField()),
                ('Courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
