# Generated by Django 4.1.2 on 2023-03-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_course'),
        ('assignments', '0006_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Rollno', models.IntegerField(unique=True)),
                ('Registration_no', models.IntegerField()),
                ('Courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
            ],
            options={
                'db_table': 'studentprofile',
            },
        ),
    ]
