# Generated by Django 4.1.2 on 2023-03-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='Registration_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
