# Generated by Django 4.1.2 on 2023-03-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_alter_studentprofile_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Subjectcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
