# Generated by Django 4.1.2 on 2023-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_alter_studentprofile_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Semester',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Sem3', 'Sem3'), ('Sem4', 'Sem4'), ('Sem5', 'Sem5'), ('Sem6', 'Sem6')], default='', max_length=100),
        ),
    ]
