# Generated by Django 4.1.2 on 2023-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='Rollno',
            field=models.IntegerField(),
        ),
    ]
