# Generated by Django 4.1.2 on 2023-03-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_alter_studentprofile_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='Sem',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem3', 'Sem3'), ('Sem5', 'Sem5')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Semester',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem3', 'Sem3'), ('Sem5', 'Sem5')], default='', max_length=100),
        ),
    ]
