# Generated by Django 4.1.2 on 2023-03-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_alter_blog_description'),
        ('assignments', '0017_rename_courseid_studentprofile_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_Number', models.IntegerField()),
                ('Assignment_Title', models.CharField(max_length=100)),
                ('Assignment_Description', models.CharField(max_length=100)),
                ('Submission_Date', models.DateField()),
                ('Assignment_Marks', models.IntegerField()),
                ('Assignment_File', models.FileField(upload_to='')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject')),
                ('Teacherprofile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.teacherprofile')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
    ]
