# Generated by Django 4.1.2 on 2023-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Sem',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem3', 'Sem3'), ('Sem5', 'Sem5')], default='', max_length=100),
        ),
    ]
