# Generated by Django 4.1.2 on 2023-03-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_assignment_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Photo',
        ),
    ]
