# Generated by Django 4.1.2 on 2023-04-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_teacherprofile_teacher_id_alter_assignment_sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Assignment_File',
            field=models.FileField(upload_to='assignment/'),
        ),
    ]
