# Generated by Django 4.1.2 on 2023-04-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0024_alter_assignment_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Teacherprofile_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignments.teacherprofile'),
        ),
    ]
