# Generated by Django 4.1.2 on 2023-04-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0031_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Teacherprofile_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignments.teacherprofile'),
        ),
    ]
