# Generated by Django 4.1.2 on 2023-04-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0038_news_teacherprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Teacherprofile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.teacherprofile'),
        ),
    ]
