# Generated by Django 4.1.2 on 2023-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0043_alter_teacherprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Sem',
            field=models.CharField(default='', max_length=100),
        ),
    ]
