# Generated by Django 4.1.2 on 2023-04-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0044_alter_assignment_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='unchecked', max_length=100)),
                ('Marks', models.FloatField(default='0')),
                ('Remarks', models.CharField(max_length=100)),
                ('Assignment_File', models.FileField(upload_to='uploaded')),
                ('Assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.studentprofile')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
    ]
