# Generated by Django 4.1.2 on 2023-04-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0045_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='Assignment_Description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
