# Generated by Django 4.1.2 on 2023-04-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0046_uploads_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='Subject_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='assignments.subject'),
        ),
    ]
