# Generated by Django 4.1.2 on 2023-04-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0047_uploads_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='Subject_id',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Subject_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='assignments.subject'),
        ),
    ]
