# Generated by Django 4.1.2 on 2023-04-26 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0049_alter_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='Submission_Date',
            field=models.DateField(default=datetime.date(2023, 4, 26)),
        ),
    ]
