# Generated by Django 4.1.2 on 2023-04-27 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0050_uploads_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='Submission_Date',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
    ]
