# Generated by Django 4.1.2 on 2023-04-28 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0051_new_date_alter_uploads_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 28)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='Submission_Date',
            field=models.DateField(default=datetime.date(2023, 4, 28)),
        ),
    ]
