# Generated by Django 4.1.2 on 2023-05-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0053_alter_new_date_alter_uploads_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='Marks',
            field=models.IntegerField(default='0'),
        ),
    ]
