# Generated by Django 4.1.2 on 2023-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0054_alter_uploads_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='Marks',
            field=models.FloatField(default='0'),
        ),
    ]
