# Generated by Django 4.1.2 on 2023-05-04 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0055_alter_uploads_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 4)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='Submission_Date',
            field=models.DateField(default=datetime.date(2023, 5, 4)),
        ),
    ]
