# Generated by Django 4.1.2 on 2023-05-14 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0058_alter_new_date_alter_uploads_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 5, 14)),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='Submission_Date',
            field=models.DateField(default=datetime.date(2023, 5, 14)),
        ),
    ]
